create table sys_oper_log
(
    oper_id        bigint auto_increment comment '日志主键'
        primary key,
    title          varchar(50)   default '' null comment '模块标题',
    business_type  int           default 0  null comment '业务类型（0其它 1新增 2修改 3删除）',
    method         varchar(100)  default '' null comment '方法名称',
    request_method varchar(10)   default '' null comment '请求方式',
    operator_type  int           default 0  null comment '操作类别（0其它 1后台用户 2手机端用户）',
    oper_name      varchar(50)   default '' null comment '操作人员',
    dept_name      varchar(50)   default '' null comment '部门名称',
    oper_url       varchar(255)  default '' null comment '请求URL',
    oper_ip        varchar(128)  default '' null comment '主机地址',
    oper_location  varchar(255)  default '' null comment '操作地点',
    oper_param     varchar(2000) default '' null comment '请求参数',
    json_result    varchar(2000) default '' null comment '返回参数',
    status         int           default 0  null comment '操作状态（0正常 1异常）',
    error_msg      varchar(2000) default '' null comment '错误消息',
    oper_time      datetime                 null comment '操作时间'
)
    comment '操作日志记录';

INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (100, '用户头像', 2, 'com.kaiyu56.system.controller.SysProfileController.avatar()', 'POST', 1, 'admin', null, '/user/profile/avatar', '127.0.0.1', '', '', '{"msg":"操作成功","imgUrl":"http://127.0.0.1:9300/statics/2021/02/21/d91f0599-f431-4220-916c-a4e7c7ccc788.jpeg","code":200}', 0, null, '2021-02-21 09:38:01');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (101, '个人信息', 2, 'com.kaiyu56.system.controller.SysProfileController.updatePwd()', 'PUT', 1, 'admin', null, '/user/profile/updatePwd', '127.0.0.1', '', 'admin123 123456', '{"msg":"操作成功","code":200}', 0, null, '2021-02-21 14:12:20');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (102, '代码生成', 6, 'com.kaiyu56.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', 'test', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 02:05:28');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (103, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 02:07:24');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (104, '菜单管理', 1, 'com.kaiyu56.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"bug","orderNum":"1","menuName":"测试","params":{},"parentId":0,"isCache":"0","path":"/test","createBy":"admin","children":[],"isFrame":"1","menuType":"M","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 02:10:18');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (105, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 02:13:49');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (106, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 02:21:46');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (107, '菜单管理', 2, 'com.kaiyu56.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"visible":"0","icon":"bug","orderNum":"0","menuName":"测试","params":{},"parentId":0,"isCache":"0","path":"/test","children":[],"createTime":1613931018000,"updateBy":"admin","isFrame":"1","menuId":2000,"menuType":"M","perms":"","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 03:54:48');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (108, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"creator":1,"gmtModify":1613923200000,"modifier":1,"gmtCreate":1613923200000,"params":{},"title":"1","parentId":1,"id":1}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 03:56:45');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (109, '代码生成', 2, 'com.kaiyu56.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/test', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 04:39:41');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (110, '代码生成', 2, 'com.kaiyu56.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/test', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 04:40:26');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (111, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 04:42:21');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (112, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 04:52:57');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (113, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"createTime":1613969678375,"remark":"奥术大师","params":{},"title":"啊哈","parentId":0}', 'null', 1, 'Invalid bound statement (not found): com.kaiyu56.test.mapper.TestMapper.insertTest', '2021-02-22 04:54:38');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (114, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"createTime":1613969692484,"remark":"奥术大师","params":{},"title":"啊哈","parentId":0}', 'null', 1, 'Invalid bound statement (not found): com.kaiyu56.test.mapper.TestMapper.insertTest', '2021-02-22 04:54:52');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (115, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"createTime":1613969953293,"remark":"奥术大师","params":{},"title":"啊哈","parentId":0}', 'null', 1, 'Invalid bound statement (not found): com.kaiyu56.test.mapper.TestMapper.insertTest', '2021-02-22 04:59:13');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (116, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"createTime":1613970092128,"remark":"asdasdasd","params":{},"title":"aga","parentId":0}', 'null', 1, 'Invalid bound statement (not found): com.kaiyu56.test.mapper.TestMapper.insertTest', '2021-02-22 05:01:32');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (117, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdasd","params":{},"title":"aga","parentId":0}', 'null', 1, 'nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property ''params''. It was either not specified and/or could not be found for the javaType (java.util.Map) : jdbcType (null) combination.
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert
### The error occurred while executing an update
### Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property ''params''. It was either not specified and/or could not be found for the javaType (java.util.Map) : jdbcType (null) combination.', '2021-02-22 05:05:56');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (118, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdasd","params":{},"title":"aga","parentId":0}', 'null', 1, 'nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property ''params''. It was either not specified and/or could not be found for the javaType (java.util.Map) : jdbcType (null) combination.
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert
### The error occurred while executing an update
### Cause: java.lang.IllegalStateException: Type handler was null on parameter mapping for property ''params''. It was either not specified and/or could not be found for the javaType (java.util.Map) : jdbcType (null) combination.', '2021-02-22 05:06:16');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (119, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdasd","id":1363717709576167426,"params":{},"title":"aga","parentId":0}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 05:10:13');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (120, '用户管理', 1, 'com.kaiyu56.system.controller.SysUserController.add()', 'POST', 1, 'admin', null, '/user', '127.0.0.1', '', '{"phonenumber":"13926096022","admin":false,"password":"$2a$10$c/Dua.JiU7e6WCX7ZY2UruOEAortA49Cub.jSPsDJjreozgGFTceG","postIds":[1,3,2],"email":"css.1999@outlook.com","nickName":"Hamster","sex":"0","deptId":100,"params":{},"userName":"css","userId":100,"createBy":"admin","roleIds":[2],"status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 05:24:08');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (121, '用户管理', 2, 'com.kaiyu56.system.controller.SysUserController.edit()', 'PUT', 1, 'admin', null, '/user', '127.0.0.1', '', '{"roles":[{"flag":false,"roleId":1,"admin":true,"dataScope":"1","params":{},"roleSort":"1","deptCheckStrictly":false,"menuCheckStrictly":false,"roleKey":"admin","roleName":"超级管理员","status":"0"}],"phonenumber":"15888888888","admin":true,"loginDate":1521171180000,"remark":"管理员","delFlag":"0","password":"","postIds":[1],"loginIp":"127.0.0.1","email":"ry@163.com","nickName":"若依","sex":"1","deptId":100,"avatar":"http://127.0.0.1:9300/statics/2021/02/21/d91f0599-f431-4220-916c-a4e7c7ccc788.jpeg","dept":{"deptName":"研发部门","leader":"若依","deptId":103,"orderNum":"1","params":{},"parentId":101,"children":[],"status":"0"},"params":{},"userName":"admin","userId":1,"createBy":"admin","roleIds":[1],"createTime":1521171180000,"status":"0"}', 'null', 1, '不允许操作超级管理员用户', '2021-02-22 05:25:04');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (122, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 05:36:57');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (123, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdas","id":1363717709576167427,"params":{},"title":"hahaha","parentId":0}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 07:55:22');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (124, '测试', 2, 'com.kaiyu56.test.controller.TestController.edit()', 'PUT', 1, 'admin', null, '/test', '127.0.0.1', '', '{"createBy":"","updateBy":"","remark":"asdasdasd","id":1,"delFlag":"0","params":{},"title":"agaasdas","parentId":0}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 08:29:20');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (125, '测试', 3, 'com.kaiyu56.test.controller.TestController.remove()', 'DELETE', 1, 'admin', null, '/test/1363717709576167429', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 08:29:27');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (126, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdasdasd","id":1363717709576167430,"params":{},"title":"asdasdas","parentId":1}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 08:29:35');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (127, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdscasdc","id":1363717709576167431,"params":{},"title":"ascasdc","parentId":9}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 08:29:56');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (128, '测试', 3, 'com.kaiyu56.test.controller.TestController.remove()', 'DELETE', 1, 'admin', null, '/test/1363717709576167430,1363717709576167431', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 08:30:03');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (129, '测试', 5, 'com.kaiyu56.test.controller.TestController.export()', 'POST', 1, 'admin', null, '/test/export', '127.0.0.1', '', '{"params":{}}', 'null', 0, null, '2021-02-22 08:30:11');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (130, '测试', 5, 'com.kaiyu56.test.controller.TestController.export()', 'POST', 1, 'admin', null, '/test/export', '127.0.0.1', '', '{"params":{}}', 'null', 0, null, '2021-02-22 08:33:33');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (131, '代码生成', 2, 'com.kaiyu56.gen.controller.GenController.synchDb()', 'GET', 1, 'admin', null, '/gen/synchDb/test', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 08:50:10');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (132, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 1, 'Encountered "#end\\r\\n" at vm/java/domain.java.vm[line 66, column 1]
Was expecting one of:
    <EOF> 
    "(" ...
    <RPAREN> ...
    <ESCAPE_DIRECTIVE> ...
    <SET_DIRECTIVE> ...
    "##" ...
    "\\\\\\\\" ...
    "\\\\" ...
    <TEXT> ...
    "*#" ...
    "*#" ...
    "]]#" ...
    <STRING_LITERAL> ...
    <IF_DIRECTIVE> ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <WORD> ...
    <BRACKETED_WORD> ...
    <IDENTIFIER> ...
    <DOT> ...
    "{" ...
    "}" ...
    <EMPTY_INDEX> ...
    ', '2021-02-22 08:50:48');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (133, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 08:52:43');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (134, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 08:52:54');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (135, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 08:53:33');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (136, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 09:02:06');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (137, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 09:02:25');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (138, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 09:15:14');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (139, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 09:18:41');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (140, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdas","params":{}}', 'null', 1, '
### Error updating database.  Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO test  ( remark )  VALUES  ( ? )
### Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
; Field ''title'' doesn''t have a default value; nested exception is java.sql.SQLException: Field ''title'' doesn''t have a default value', '2021-02-22 09:36:19');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (141, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdas","params":{}}', 'null', 1, '
### Error updating database.  Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO test  ( remark )  VALUES  ( ? )
### Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
; Field ''title'' doesn''t have a default value; nested exception is java.sql.SQLException: Field ''title'' doesn''t have a default value', '2021-02-22 09:37:52');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (142, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"asdasdas","params":{}}', 'null', 1, '
### Error updating database.  Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO test  ( remark )  VALUES  ( ? )
### Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
; Field ''title'' doesn''t have a default value; nested exception is java.sql.SQLException: Field ''title'' doesn''t have a default value', '2021-02-22 09:37:52');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (143, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"大叔大婶多","params":{}}', 'null', 1, '
### Error updating database.  Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO test  ( remark )  VALUES  ( ? )
### Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
; Field ''title'' doesn''t have a default value; nested exception is java.sql.SQLException: Field ''title'' doesn''t have a default value', '2021-02-22 09:38:24');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (144, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"大叔大婶多","params":{}}', 'null', 1, '
### Error updating database.  Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
### The error may exist in com/kaiyu56/test/mapper/TestMapper.java (best guess)
### The error may involve com.kaiyu56.test.mapper.TestMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO test  ( remark )  VALUES  ( ? )
### Cause: java.sql.SQLException: Field ''title'' doesn''t have a default value
; Field ''title'' doesn''t have a default value; nested exception is java.sql.SQLException: Field ''title'' doesn''t have a default value', '2021-02-22 09:39:10');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (145, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"大叔大婶多","params":{},"title":"奥术大师大所","parentId":0}', 'null', 1, 'nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named ''tableName'' in ''class com.kaiyu56.test.domain.Test''', '2021-02-22 09:42:19');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (146, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"大叔大婶多","params":{},"title":"奥术大师大所","parentId":0}', 'null', 1, 'nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named ''tableName'' in ''class com.kaiyu56.test.domain.Test''', '2021-02-22 09:42:36');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (147, '测试', 1, 'com.kaiyu56.test.controller.TestController.add()', 'POST', 1, 'admin', null, '/test', '127.0.0.1', '', '{"remark":"大叔大婶多","id":1363717709576167432,"params":{},"title":"奥术大师大所","parentId":0}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 09:43:49');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (148, '测试', 2, 'com.kaiyu56.test.controller.TestController.edit()', 'PUT', 1, 'admin', null, '/test', '127.0.0.1', '', '{"createBy":"","updateBy":"","remark":"大叔大婶多asdas","id":1363717709576167432,"delFlag":"0","params":{},"title":"奥术大师大所","parentId":0}', '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 09:43:55');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (149, '测试', 3, 'com.kaiyu56.test.controller.TestController.remove()', 'DELETE', 1, 'admin', null, '/test/2,123,1363717709576167432', '127.0.0.1', '', null, '{"msg":"操作成功","code":200}', 0, null, '2021-02-22 09:44:04');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (150, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 09:53:48');
INSERT INTO LMS.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time) VALUES (151, '代码生成', 8, 'com.kaiyu56.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', null, 'null', 0, null, '2021-02-22 10:04:04');